### ISSUE TITLE
ant-design-pro 例子报错

### ISSUE THREAD

**Issue by yaodong5063** [umijs/umi-next#379]
![image](https://user-images.githubusercontent.com/37628562/154905683-2f64c0ac-d8fd-471c-835e-dfc3bb4b474b.png)
![image](https://user-images.githubusercontent.com/37628562/154905712-95d75440-c60d-4402-8f89-c3e0e994faad.png)

环境：window 11

**Comment by yaodong5063** [comment]
本地启动报错
error - AssertionError [ERR_ASSERTION]: filePath not found of common-module
    at Dep.<anonymous> (C:\demo\node_modules\@umijs\mfsu\dist\dep\dep.js:67:34)

filePath 找不到，node版本16.14.0
@sorrycc

**Comment by yaodong5063** [comment]
error - AssertionError [ERR_ASSERTION]: filePath not found of dva
    at Dep.<anonymous> (C:\demo\node_modules\@umijs\mfsu\dist\dep\dep.js:67:34)
    at Generator.next (<anonymous>)
    at fulfilled (C:\demo\node_modules\@umijs\mfsu\dist\dep\dep.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: null,
  expected: true,
  operator: '=='

**Comment by yaodong5063** [comment]
success Saved lockfile.
$ umi generate tmp
error - Error: Generator tmp not found.

安装的时候一直 使用这个命令
 umi generate tmp

**Comment by yaodong5063** [comment]
Uncaught (in promise) ScriptExternalLoadError: Loading script failed.
(timeout: http://127.0.0.1:8001/mf-va_remoteEntry.js)
while loading "./C:/demo/node_modules/@umijs/bundler-webpack/client/client/client.js" from webpack/container/reference/mf
    at Object.webpack/container/reference/mf (mf-va_remoteEntry.js":1:1)
    at Object.options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at handleFunction (remotes loading:2853:1)
    at remotes loading:2872:1
    at Array.forEach (<anonymous>)
    at Object.__webpack_require__.f.remotes (remotes loading:2835:1)
    at ensure chunk:6:1
    at Array.reduce (<anonymous>)
    at Function.__webpack_require__.e

**Comment by sorrycc** [comment]
有问题再 reopen。
