### ISSUE TITLE
使用npx create-umi@nextc创建项目报错。

### ISSUE THREAD

**Issue by Iveon** [umijs/umi-next#391]
> npx create-umi@next
Need to install the following packages:
  create-umi@next
Ok to proceed? (y)
√ Pick Npm Client » yarn
√ Pick Bpm Registry » npm

...

> Create failed, spawnSync yarn ENOENT
Error: spawnSync yarn ENOENT
    at Object.spawnSync (node:internal/child_process:1083:20)
    at spawnSync (node:child_process:812:24)
    at installWithNpmClient (...\npm-cache\_npx\3f4d706d21e95758\node_modules\@umijs\utils\dist\npmClient.js:35:17)
    at ...\npm-cache\_npx\3f4d706d21e95758\node_modules\create-umi\dist\index.js:104:42
    at Generator.next (<anonymous>)
    at fulfilled (...\npm-cache\_npx\3f4d706d21e95758\node_modules\create-umi\dist\index.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawnSync yarn',
  path: 'yarn',
  spawnargs: [ '' ]
}

**Comment by chenliangngng** [comment]
我选taobao源创建成功

**Comment by szzend** [comment]
我也报错

Create failed, spawnSync pnpm ENOENT
Error: spawnSync pnpm ENOENT
    at Object.spawnSync (node:internal/child_process:1083:20)
    at spawnSync (node:child_process:812:24)
    at installWithNpmClient (D:\.pnpm-store\v3\tmp\_npx\18056\5\node_modules\.pnpm\@umijs+utils@4.0.0-rc.3\node_modules\@umijs\utils\dist\npmClient.js:35:17)
    at D:\.pnpm-store\v3\tmp\_npx\18056\5\node_modules\.pnpm\create-umi@4.0.0-rc.3\node_modules\create-umi\dist\index.js:104:42
    at Generator.next (<anonymous>)
    at fulfilled (D:\.pnpm-store\v3\tmp\_npx\18056\5\node_modules\.pnpm\create-umi@4.0.0-rc.3\node_modules\create-umi\dist\index.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawnSync pnpm',
  path: 'pnpm',
  spawnargs: [ 'install' ]
}
