### ISSUE TITLE
vite 模式跑 examples/boilerplates 失败

### ISSUE THREAD

**Issue by sorrycc** [umijs/umi-next#401]
报错堆栈。

```
Uncaught SyntaxError: Unexpected identifier
react_devtools_backend.js:4061 The above error occurred in the <InnerLoadable2> component:

    at InnerLoadable2 (http://127.0.0.1:8000/node_modules/.vite/@fs_Users_chencheng_code_github_com_umijs_umi-next_packages_renderer-react.js?v=a812227f:460:34)
    at LoadableWithChunkExtractor2
    at Loadable
    at RemoteComponent (http://127.0.0.1:8000/node_modules/.vite/@fs_Users_chencheng_code_github_com_umijs_umi-next_packages_renderer-react.js?v=a812227f:713:48)
    at Outlet (http://127.0.0.1:8000/node_modules/.vite/chunk-AENJP7JA.js?v=a812227f:654:26)
    at div
    at Layout
    at InnerLoadable2 (http://127.0.0.1:8000/node_modules/.vite/@fs_Users_chencheng_code_github_com_umijs_umi-next_packages_renderer-react.js?v=a812227f:460:34)
    at LoadableWithChunkExtractor2
    at Loadable
    at RemoteComponent (http://127.0.0.1:8000/node_modules/.vite/@fs_Users_chencheng_code_github_com_umijs_umi-next_packages_renderer-react.js?v=a812227f:713:48)
    at Routes (http://127.0.0.1:8000/node_modules/.vite/@fs_Users_chencheng_code_github_com_umijs_umi-next_packages_renderer-react.js?v=a812227f:742:28)
    at Router (http://127.0.0.1:8000/node_modules/.vite/chunk-AENJP7JA.js?v=a812227f:661:15)
    at BrowserRoutes (http://127.0.0.1:8000/node_modules/.vite/@fs_Users_chencheng_code_github_com_umijs_umi-next_packages_renderer-react.js?v=a812227f:721:11)
    at div
    at Foo (http://127.0.0.1:8000/app.tsx:44:23)
    at div
    at Foo (http://127.0.0.1:8000/app.tsx:44:23)
    at div
    at Foo (http://127.0.0.1:8000/app.tsx:44:23)
    at div
    at Foo (http://127.0.0.1:8000/app.tsx:44:23)
    at div
    at Foo (http://127.0.0.1:8000/app.tsx:44:23)
```

<img width="1278" alt="image" src="https://user-images.githubusercontent.com/35128/155934906-dc482b9d-2a9b-4c36-acdd-9751f9762835.png">

**Comment by PeachScript** [comment]
确认是 Vite 模式下不支持数组型 externals 配置导致的，已提交 PR 做配置 schema 校验
