### ISSUE TITLE
怎么样兼容ie11，在targets设置ie11后,umi3需要设置esbuild:"es5"，这个没有了应该咋设置

### ISSUE THREAD

**Issue by aadog** [umijs/umi-next#538]
怎么样兼容ie11，在targets设置ie11后,umi3需要设置esbuild:"es5"，这个没有了应该咋设置

**Comment by fz6m** [comment]
ie 已经被淘汰了。

1. vue3 不再支持 ie
2. react 18 不再支持 ie
3. esbuild / swc 等现代打包器不支持 ie

**Comment by aadog** [comment]
是说umi4不在支持ie11吗。。

**Comment by sorrycc** [comment]
试试配置 jsMinifierOptions: { target: 'es5' }

**Comment by aadog** [comment]
```
PS C:\Users\pwt\src\sp\spUI> yarn build
yarn run v1.22.17
$ max build
error - undefined
299.js from Terser plugin
Transform failed with 3 errors:
299.js:4884:13: ERROR: Transforming for-of loops to the configured target environment ("es5") is not supported yet
299.js:4886:13: ERROR: Transforming for-of loops to the configured target environment ("es5") is not supported yet
299.js:4893:13: ERROR: Transforming for-of loops to the configured target environment ("es5") is not supported yet
Error: Transform failed with 3 errors:
299.js:4884:13: ERROR: Transforming for-of loops to the configured target environment ("es5") is not supported yet
299.js:4886:13: ERROR: Transforming for-of loops to the configured target environment ("es5") is not supported yet
299.js:4893:13: ERROR: Transforming for-of loops to the configured target environment ("es5") is not supported yet
    at failureErrorWithLog (C:\Users\pwt\src\sp\spUI\node_modules\esbuild\lib\main.js:1599:15)
    at C:\Users\pwt\src\sp\spUI\node_modules\esbuild\lib\main.js:1388:29
    at C:\Users\pwt\src\sp\spUI\node_modules\esbuild\lib\main.js:662:9
    at handleIncomingPacket (C:\Users\pwt\src\sp\spUI\node_modules\esbuild\lib\main.js:759:9)
    at Socket.readFromStdout (C:\Users\pwt\src\sp\spUI\node_modules\esbuild\lib\main.js:629:7)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)
error - undefined
umi.js from Terser plugin
Transform failed with 214 errors:
umi.js:3042:0: ERROR: Transforming const to the configured target environment ("es5") is not supported yet
umi.js:3067:2: ERROR: Transforming let to the configured target environment ("es5") is not supported yet
umi.js:3067:6: ERROR: Transforming destructuring to the configured target environment ("es5") is not supported yet
umi.js:3072:2: ERROR: Transforming let to the configured target environment ("es5") is not supported yet
umi.js:3080:2: ERROR: Transforming let to the configured target environment ("es5") is not supported yet
...
Error: Transform failed with 214 errors:
umi.js:3042:0: ERROR: Transforming const to the configured target environment ("es5") is not supported yet
umi.js:3067:2: ERROR: Transforming let to the configured target environment ("es5") is not supported yet
umi.js:3067:6: ERROR: Transforming destructuring to the configured target environment ("es5") is not supported yet
umi.js:3072:2: ERROR: Transforming let to the configured target environment ("es5") is not supported yet
umi.js:3080:2: ERROR: Transforming let to the configured target environment ("es5") is not supported yet
...
    at failureErrorWithLog (C:\Users\pwt\src\sp\spUI\node_modules\esbuild\lib\main.js:1599:15)
    at C:\Users\pwt\src\sp\spUI\node_modules\esbuild\lib\main.js:1388:29
    at C:\Users\pwt\src\sp\spUI\node_modules\esbuild\lib\main.js:662:9
    at handleIncomingPacket (C:\Users\pwt\src\sp\spUI\node_modules\esbuild\lib\main.js:759:9)
    at Socket.readFromStdout (C:\Users\pwt\src\sp\spUI\node_modules\esbuild\lib\main.js:629:7)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)
info  - Memory Usage: 430.49 MB (RSS: 957.63 MB)
error - Error: ERROR in 299.js
299.js from Terser plugin
Transform failed with 3 errors:
299.js:4884:13: ERROR: Transforming for-of loops to the configured target environment ("es5") is not supported yet
299.js:4886:13: ERROR: Transforming for-of loops to the configured target environment ("es5") is not supported yet
299.js:4893:13: ERROR: Transforming for-of loops to the configured target environment ("es5") is not supported yet
Error: Transform failed with 3 errors:
299.js:4884:13: ERROR: Transforming for-of loops to the configured target environment ("es5") is not supported yet
299.js:4886:13: ERROR: Transforming for-of loops to the configured target environment ("es5") is not supported yet
299.js:4893:13: ERROR: Transforming for-of loops to the configured target environment ("es5") is not supported yet
    at failureErrorWithLog (C:\Users\pwt\src\sp\spUI\node_modules\esbuild\lib\main.js:1599:15)
    at C:\Users\pwt\src\sp\spUI\node_modules\esbuild\lib\main.js:1388:29
    at C:\Users\pwt\src\sp\spUI\node_modules\esbuild\lib\main.js:662:9
    at handleIncomingPacket (C:\Users\pwt\src\sp\spUI\node_modules\esbuild\lib\main.js:759:9)
    at Socket.readFromStdout (C:\Users\pwt\src\sp\spUI\node_modules\esbuild\lib\main.js:629:7)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)

ERROR in umi.js
umi.js from Terser plugin
Transform failed with 214 errors:
umi.js:3042:0: ERROR: Transforming const to the configured target environment ("es5") is not supported yet
umi.js:3067:2: ERROR: Transforming let to the configured target environment ("es5") is not supported yet
umi.js:3067:6: ERROR: Transforming destructuring to the configured target environment ("es5") is not supported yet
umi.js:3072:2: ERROR: Transforming let to the configured target environment ("es5") is not supported yet
umi.js:3080:2: ERROR: Transforming let to the configured target environment ("es5") is not supported yet
...
Error: Transform failed with 214 errors:
umi.js:3042:0: ERROR: Transforming const to the configured target environment ("es5") is not supported yet
umi.js:3067:2: ERROR: Transforming let to the configured target environment ("es5") is not supported yet
umi.js:3067:6: ERROR: Transforming destructuring to the configured target environment ("es5") is not supported yet
umi.js:3072:2: ERROR: Transforming let to the configured target environment ("es5") is not supported yet
umi.js:3080:2: ERROR: Transforming let to the configured target environment ("es5") is not supported yet
...
    at failureErrorWithLog (C:\Users\pwt\src\sp\spUI\node_modules\esbuild\lib\main.js:1599:15)
    at C:\Users\pwt\src\sp\spUI\node_modules\esbuild\lib\main.js:1388:29
    at C:\Users\pwt\src\sp\spUI\node_modules\esbuild\lib\main.js:662:9
    at handleIncomingPacket (C:\Users\pwt\src\sp\spUI\node_modules\esbuild\lib\main.js:759:9)
    at Socket.readFromStdout (C:\Users\pwt\src\sp\spUI\node_modules\esbuild\lib\main.js:629:7)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)

webpack compiled with 2 errors
    at C:\Users\pwt\src\sp\spUI\node_modules\@umijs\bundler-webpack\dist\build.js:62:32
    at finalCallback (C:\Users\pwt\src\sp\spUI\node_modules\@umijs\bundler-webpack\compiled\webpack\index.js:61541:32)
    at C:\Users\pwt\src\sp\spUI\node_modules\@umijs\bundler-webpack\compiled\webpack\index.js:61558:13
    at Hook.eval [as callAsync] (eval at create (C:\Users\pwt\src\sp\spUI\node_modules\@umijs\bundler-webpack\compiled\tapable\index.js:1:7682), <anonymous>:15:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Users\pwt\src\sp\spUI\node_modules\@umijs\bundler-webpack\compiled\tapable\index.js:1:4851)
    at onCompiled (C:\Users\pwt\src\sp\spUI\node_modules\@umijs\bundler-webpack\compiled\webpack\index.js:61556:21)
    at C:\Users\pwt\src\sp\spUI\node_modules\@umijs\bundler-webpack\compiled\webpack\index.js:62283:17
    at Hook.eval [as callAsync] (eval at create (C:\Users\pwt\src\sp\spUI\node_modules\@umijs\bundler-webpack\compiled\tapable\index.js:1:7682), <anonymous>:15:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Users\pwt\src\sp\spUI\node_modules\@umijs\bundler-webpack\compiled\tapable\index.js:1:4851)
    at C:\Users\pwt\src\sp\spUI\node_modules\@umijs\bundler-webpack\compiled\webpack\index.js:62279:33
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS C:\Users\pwt\src\sp\spUI> yarn build
yarn run v1.22.17
$ max build
event - Compiled successfully in 71295 ms (4579 modules)
info  - Memory Usage: 408.57 MB (RSS: 960.67 MB)
event - Build index.html
Done in 85.33s.

```

**Comment by aadog** [comment]
```
import {defineConfig} from "@umijs/max";

export default defineConfig({
    npmClient: 'yarn',
    request: {},
    antd: {},
    model: {},
    access: {},
    initialState: {},
    targets: {
        ie: 11,
    },
    jsMinifierOptions: {
        target: 'es5'
    },
    proxy: {
        '/api/': {
            target: 'http://127.0.0.1:8080',
            changeOrigin: true,
        },
    },
    routes: [
        {
            path: '/auth',
            routes: [
                {name: '认证首页', path: '/auth', component: './Auth'},
                {name: '登录', path: '/auth/login', component: './Auth/Login'},
                {name: '退出登录', path: '/auth/loginOut', component: './Auth/LoginOut'},
            ]
        },
        {
            path: '/user',
            component: './User/_layout',
            routes: [
                {path: '/user', redirect: '/user/index'},
                {name: '系统配置', icon: 'icon-table', path: '/user/webConfig', component: './User/WebConfig'},
                {name: '用户主页', icon: 'icon-table', path: '/user/index', component: './User/Account/Settings'},
                {name: '地址管理', icon: 'icon-table', path: '/user/addresss', component: './User/Addresss'},
                {name: '消费日志', icon: 'icon-table', path: '/user/moneylogs', component: './User/MoneyLogs'},
                {
                    name: '自动确认收货',
                    icon: 'icon-table',
                    path: '/user/AutoConfirmReceipt',
                    component: './User/AutoConfirmReceipt'
                },
                {name: '账单下载', icon: 'icon-table', path: '/user/Payment', component: './User/Payment'},
                {name: '订单管理', icon: 'icon-table', path: '/user/orders', component: './User/Orders'},
                {name: '用户管理', icon: 'icon-table', path: '/user/users', component: './User/Users'},
                {name: '站点管理', icon: 'icon-table', path: '/user/countrys', component: './User/Countrys'},
                {name: '客户端用户管理', icon: 'icon-table', path: '/user/clientusers', component: './User/ClientUsers'},
            ],
        },
    ]
})

```

**Comment by sorrycc** [comment]
1、esbuild 不支持转换成 es5，这条路行不通，需要在给到 esbuild 之前就转成 es5
2、ie 11 一定要转成 es5 吗？查了下 const 之类 ie 11 也是支持的
3、umi 3 有 nodeModulesTransform: { type: 'all' }，这个 umi 4 暂不支持，因为太耗性能了

**Comment by cnyballk** [comment]
可以不用 esbuild，将  jsMinifier 切换为其他的压缩器，其他选项有：terser，swc，uglifyJs，none 
例如：
```js
export default {
   jsMinifier: 'uglifyJs'
}
```

**Comment by flyuuo9** [comment]
https://webpack.js.org/migrate/5/#need-to-support-an-older-browser-like-ie-11
