### ISSUE TITLE
想请问一下MFSU可以用在Webpack5的Vue2项目中吗

### ISSUE THREAD

**Issue by CrabSAMA** [umijs/umi-next#592]
如题，尝试在现有项目中按照教程引入了MFSU，项目跑起来后有这一段报错
```
error - AssertionError [ERR_ASSERTION]: file type not supported for onlineEditor.vue.
    at /Users/crab.huang/Project/abtest.web/node_modules/@umijs/mfsu/dist/dep/getExposeFromContent.js:33:30
    at Generator.next (<anonymous>)
    at /Users/crab.huang/Project/abtest.web/node_modules/@umijs/mfsu/dist/dep/getExposeFromContent.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/crab.huang/Project/abtest.web/node_modules/@umijs/mfsu/dist/dep/getExposeFromContent.js:4:12)
    at getExposeFromContent (/Users/crab.huang/Project/abtest.web/node_modules/@umijs/mfsu/dist/dep/getExposeFromContent.js:20:12)
    at Dep.<anonymous> (/Users/crab.huang/Project/abtest.web/node_modules/@umijs/mfsu/dist/dep/dep.js:74:74)
    at Generator.next (<anonymous>)
    at /Users/crab.huang/Project/abtest.web/node_modules/@umijs/mfsu/dist/dep/dep.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/crab.huang/Project/abtest.web/node_modules/@umijs/mfsu/dist/dep/dep.js:23:12)
    at Dep.buildExposeContent (/Users/crab.huang/Project/abtest.web/node_modules/@umijs/mfsu/dist/dep/dep.js:54:16)
    at DepBuilder.<anonymous> (/Users/crab.huang/Project/abtest.web/node_modules/@umijs/mfsu/dist/depBuilder/depBuilder.js:66:43)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/crab.huang/Project/abtest.web/node_modules/@umijs/mfsu/dist/depBuilder/depBuilder.js:5:58)
    at runMicrotasks (<anonymous>) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
```
然后是访问项目会白屏，观察 devtool 中 network，是卡在这一项了：
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/40541269/162619642-ac49794b-a4ed-4521-897e-e02ca5f430ed.png">

看报错是说不支持这个文件类型，点击进到文件里面查看也确实没有：
```js
// Support Assets Files
        if (opts.filePath &&
            /\.(json|svg|png|jpe?g|avif|gif|webp|ico|eot|woff|woff2|ttf|txt|text|mdx?)$/.test(opts.filePath)) {
            return `
import _ from '${opts.dep.file}';
export default _;`.trim();
        }
        (0, assert_1.default)(/(js|jsx|mjs|ts|tsx)$/.test(opts.filePath), `file type not supported for ${(0, path_1.basename)(opts.filePath)}.`);
        const { exports, isCJS } = yield (0, getModuleExports_1.getModuleExports)({
            content: opts.content,
            filePath: opts.filePath,
        });
```

总结：想请问一下MFSU可以用在Webpack5的Vue2项目中吗

**Comment by fz6m** [comment]
Vue 圈使用 vite 可以解速度问题。

**Comment by CrabSAMA** [comment]
> Vue 圈使用 vite 可以解速度问题。

确实也是解决的办法，但是在想要 webpack 生态下的优势并兼顾速度，就观察到了最近 umi 的 mfsu，所以想问一下是确实不支持吗？ @fz6m

**Comment by xierenyuan** [comment]
> > Vue 圈使用 vite 可以解速度问题。
> 
> 确实也是解决的办法，但是在想要 webpack 生态下的优势并兼顾速度，就观察到了最近 umi 的 mfsu，所以想问一下是确实不支持吗？ @fz6m

vue3 是支持的vue 2没有试过, 理论上应该以是支持的.
