### ISSUE TITLE
umi4 没有有devServer配置，需要设置port，host，headers如何处理？

### ISSUE THREAD

**Issue by liangskyli** [umijs/umi-next#824]
umi3 有devServer配置，可以设置port，host，headers，umi4没有看到暴露出来，需要设置这些东西，要如何配置？

**Comment by sorrycc** [comment]
用 .env，设置 PORT 和 HOST。headers 是啥需求，dev 时需要吗？

**Comment by liangskyli** [comment]
需要，qiankun项目需要headers配置跨域配置，dev下，配置主子qiankun应用
之前的umi3配置：
```ts
devServer: {
      port: (packageConfig as any).devPort,
      host: (packageConfig as any).devHost,
      headers: {
        'Access-Control-Allow-Headers': 'trace-id,x-requested-with',
        'Access-Control-Allow-Origin': 'http://localhost:6001',
        'Access-Control-Allow-Methods': 'POST,GET,PUT,OPTIONS,DELETE',
        'Access-Control-Allow-Credentials': 'true',
      },
    },
```

**Comment by sorrycc** [comment]
headers 的问题试下最新的 rc，可能在 https://github.com/umijs/umi-next/pull/805 下已解。

**Comment by liangskyli** [comment]
headers 的问题在4.0.0-rc.21版本可以了！
但是：qiankun主应用沙箱开strictStyleIsolation时，运行报错!
如果使用experimentalStyleIsolation，运行就正常，项目之前使用了strictStyleIsolation隔离，跨部门使用，希望能支持 shadow dom隔离。

```
mf-dep____vendor.6c5eb1ad.js:63858 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'contains')
while loading "./antd-mobile" from webpack/container/reference/mf_****_h5
    at HTMLHeadElement.appendChildOrInsertBefore [as appendChild] (mf-dep____vendor.6c5eb1ad.js:63858:42)
    at createStylesheet (mf-va_remoteEntry.js:249:18)
    at eval (mf-va_remoteEntry.js:271:14)
    at new Promise (<anonymous>)
    at loadStylesheet (mf-va_remoteEntry.js:267:20)
    at Object.__webpack_require__.f.miniCss (mf-va_remoteEntry.js:283:58)
    at eval (mf-va_remoteEntry.js:102:40)
    at Array.reduce (<anonymous>)
    at Function.__webpack_require__.e (mf-va_remoteEntry.js:101:67)
    at Object../antd-mobile (mf-va_remoteEntry.js:410:421)
    at get (mf-va_remoteEntry.js:525:23)
    at handleFunction (remotes loading:361:1)
    at onInitialized (remotes loading:373:1)
    at eval (remotes loading:363:1)
    at async Promise.all (:6001/****/index 0)
    at async eval (handle-error.ts:6:1)
```

配置为：

```
sandbox: {
      strictStyleIsolation: true,
 },
```

**Comment by sorrycc** [comment]
由于缺乏足够的信息，我们暂时关闭了该 Issue。请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example) 以重新开启 Issue。谢谢。

**Comment by liangskyli** [comment]
qiankun 的bug,已经提供复现demo给qiankun处理了！
