### ISSUE TITLE
umi的配置中添加request之后，umi lint不通过

### ISSUE THREAD

**Issue by ZYChimne** [umijs/umi-next#855]
配置中添加request，请求正常
```ts
import { defineConfig } from 'umi';
export default defineConfig({
  request: {
    dataField: '',
  },
});
```
但是在umi lint的时候，提示
```bash
fatal - AssertionError [ERR_ASSERTION]: Invalid config keys: request
    at Function.validateConfig (~/node_modules/@umijs/core/dist/config/config.js:159:30)
    at Config.getConfig (~/node_modules/@umijs/core/dist/config/config.js:38:16)
    at Service.resolveConfig (~/node_modules/@umijs/core/dist/service/service.js:301:38)
    at Service.run (~/node_modules/@umijs/core/dist/service/service.js:233:54)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Service.run2 (~/node_modules/umi/dist/service/service.js:36:16)
    at async Object.run (~/node_modules/umi/dist/cli/cli.js:37:13) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
```
.eslint.js的配置如下
```js
module.exports = {
  extends: require.resolve('@umijs/max/eslint'),
  rules: {
    'react-hooks/exhaustive-deps': 'warn',
    '@typescript-eslint/no-unused-vars': 'warn',
  },
};
```
版本：
umijs/max: 4.0.0-rc.21，
node：16.15.0

**Comment by fz6m** [comment]
使用 `@umijs/max` 时，所有命令应该是 `max <command>` ，而不是 `umi <command>` 

请尝试 `max lint`
