### ISSUE TITLE
examples/with-dva 运行报错 filePath not found of redux

### ISSUE THREAD

**Issue by YeWills** [umijs/umi-next#873]
电脑环境如下：
win10电脑
pnpm@6.20.0
npm@6.14.16
node@16.13.2
npminstall@5.4.1

问题描述：
将umi-next代码 git clone 下来后， 切换到tag v4.0.0-rc.22 版本上【以下问题在 v4.0.0-rc.15 也存在】， 依次执行：
`pnpm install` `pnpm build`
然后 `cd /examples/with-dva` 后，运行 `npm start` 命令报错，
具体情况如下：
` /d/git/umi/travel-unext-copy1/examples/with-dva (version4.0.0-rc.22)        
$ npm start

> start      
> npm run dev
> dev    
> umi dev

info  - Umi v4.0.0-rc.22
ready - App listening at http://127.0.0.1:8000
event - Compiled successfully in 6234 ms (546 modules)
info  - MFSU buildDeps since cacheDependency has changed
wait  - Compiling...
event - Compiled successfully in 570 ms (534 modules)
wait  - Compiling...
event - Compiled successfully in 280 ms (534 modules)
info  - Memory Usage: 204.33 MB (RSS: 294.81 MB)
error - AssertionError [ERR_ASSERTION]: filePath not found of redux
    at Dep.buildExposeContent (D:\git\umi\travel-unext-copy1\packages\mfsu\dist\dep\dep.js:54:30)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async DepBuilder.writeMFFiles (D:\git\umi\travel-unext-copy1\packages\mfsu\dist\depBuilder\depBuilder.js:103:29)
    at async DepBuilder.build (D:\git\umi\travel-unext-copy1\packages\mfsu\dist\depBuilder\depBuilder.js:73:13)
    at async MFSU.buildDeps (D:\git\umi\travel-unext-copy1\packages\mfsu\dist\mfsu.js:210:9) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: null,
  expected: true,
  operator: '=='
}
`
运行umi文档正常，根目录下执行：
`
  pnpm doc:deps
  pnpm doc:dev
`
具体情况如下：
` /d/git/umi/travel-unext-copy1 (version4.0.0-rc.22)
$ pnpm doc:dev

> @ doc:dev D:\git\umi\travel-unext-copy1
> umi dev

info  - Umi v4.0.0-rc.22
ready - App listening at http://127.0.0.1:8000
event - Compiled successfully in 133336 ms (913 modules)
info  - Memory Usage: 822.29 MB (RSS: 2047.6 MB)
`
浏览器访问 http://127.0.0.1:8000 可正常访问umi文档。

**Comment by xierenyuan** [comment]
git clone 的目录是否是  `travel-unext-copy1` 建议 git clone 的时候 保留 `umi-next` 目录  mfsu 有针对 项目工作区做一些处理
