### ISSUE TITLE
使用 create-umi 选择 Enterprise App 模板，运行报错

### ISSUE THREAD

**Issue by b1ngx** [umijs/umi-next#914]
```
❯ npx create-umi@next
√ Pick Umi App Template » Enterprise App
√ Pick Npm Client » pnpm
√ Pick Npm Registry » taobao

❯ pnpm dev

$ max dev
info  - Umi v4.0.0-rc.24
warn  - Invalidate webpack cache since mfsu cache is missing
ready - App listening at http://127.0.0.1:8000
event - Compiled successfully in 2307 ms (576 modules)
info  - MFSU buildDeps since cacheDependency has changed
wait  - Compiling...
event - Compiled successfully in 104 ms (544 modules)
error - AssertionError [ERR_ASSERTION]: filePath not found of E:webui
ode_modules@ant-designpro-layout
    at Dep.buildExposeContent (E:\webui\node_modules\@umijs\mfsu\dist\dep\dep.js:54:30)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async DepBuilder.writeMFFiles (E:\webui\node_modules\@umijs\mfsu\dist\depBuilder\depBuilder.js:103:29)
    at async DepBuilder.build (E:\webui\node_modules\@umijs\mfsu\dist\depBuilder\depBuilder.js:73:13)
    at async MFSU.buildDeps (E:\webui\node_modules\@umijs\mfsu\dist\mfsu.js:212:9) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: null,
  expected: true,
  operator: '=='
}
Error: ENOENT: no such file or directory, open 'E:\webui\node_modules\.cache\mfsu\mf-va_remoteEntry.js'
    at Object.openSync (node:fs:585:3)
    at readFileSync (node:fs:453:35)
    at E:\webui\node_modules\@umijs\mfsu\dist\mfsu.js:239:63
    at DepBuilder.onBuildComplete (E:\webui\node_modules\@umijs\mfsu\dist\depBuilder\depBuilder.js:95:13)
    at E:\webui\node_modules\@umijs\mfsu\dist\mfsu.js:233:37
    at Layer.handle [as handle_request] (E:\webui\node_modules\@umijs\bundler-utils\compiled\express\index.js:171:647)
    at trim_prefix (E:\webui\node_modules\@umijs\bundler-utils\compiled\express\index.js:164:2659)
    at E:\webui\node_modules\@umijs\bundler-utils\compiled\express\index.js:164:2215
    at Function.process_params (E:\webui\node_modules\@umijs\bundler-utils\compiled\express\index.js:164:2798)
    at next (E:\webui\node_modules\@umijs\bundler-utils\compiled\express\index.js:164:2115)
info  - Memory Usage: 223.53 MB (RSS: 322.49 MB)
```

**Comment by fz6m** [comment]
尝试删除 `node_modules` 后重新 `pnpm i` 安装依赖，再启动项目。

若还存在问题，请提供一个可以复现的 demo （我这里本地没有问题）

**Comment by b1ngx** [comment]
操作系统: Windows 10 企业版 21H1
node: `v16.15.0`
pnpm:  `v7.3.0`
yarn: `v1.22.18`

尝试多次，新建的项目就报此错误

```
npx create-umi@next

pnpm dev
```
